---
title: "treat_COD_1"
author: "Benjamin DAUTRIF"
date: "2023-10-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r OPEN, echo=TRUE}
#_______________________________________________________________________________
# Open dataset :
url = "~/UN/HDX/HDX_data/Iraq - Subnational Population Statistics/irq_admpop_adm0_2021.csv"

irq_admpop_adm0_2021 <-
  read_csv(
    url
  )
#_______________________________________________________________________________
```

```{r TREAT 1, echo=TRUE}
# Age pyramid for specifique gender and livehood 
# SEX = ["M" / "F"]
# LIVEHOOD = ["RURAL" / "URBAN"]
#_______________________________________________________________________________
# Variables declaration : 
dts =mex

gender = c("F","M")
livehood = c("RURAL","URBAN")

#_______________________________________________________________________________
# Functions declaration :

# - Select in GENDER :
selct_gender <- function(x,y){
  return(x%>% select(starts_with(y)))
}
# - Select in LIVEHOOD :
selct_livehood <- function(x,y){
  return(x%>% select(contains(y)))
  }

# - Select each GENDER per LIVEHOOD :
selct_age_livehood <-
  function(x,
           y = c("F", "M"),
           z = c("RURAL", "URBAN")) {
    temp = lapply(gender, function(X) {
      return(selct_gender(x, X))
    })
    
    res = c()
    for (i in seq(1, length(temp))) {
      res = append(res, lapply(z, function(X) {
        return(selct_livehodd(pluck(temp, i), X))
      }))
    }

return(res)
  }
#_______________________________________________________________________________
```

```{r RENDER 1, echo=TRUE}
#_______________________________________________________________________________
# Plot AGE-PYRAMIDs :
# Comparing GENDERs for each LIVEHOOD :
res = pyramids_age_livehood(x=dts)
for(i in seq(1,2)){
  z=i+2
  barplot(rbind(t(pluck(res, i)), t(pluck(res, z))),
          horiz = TRUE,
          beside = TRUE,
          main = paste("Age pyramide = ",livehood[i]," : F Vs M ; iraq"))
}

```


```{r LIVEHOOD, echo=TRUE}
# Comparing LIVEHOODs for each GENDER :
G=1
for(i in c(1,3)){
  z=i+1
  barplot(rbind(t(pluck(res, i)), t(pluck(res, z))),
          horiz = TRUE,
          beside = TRUE,
          main = paste("Age pyramide = ",gender[G]," : RURAL Vs URBAN ; iraq"))
  G=G+1
}
#_______________________________________________________________________________

genders <- c("F","M","T")
token_grid = mex%>%select(starts_with("F"))%>%names()%>%str_sub(start=2)

Y = lapply(genders, function(x){
  y <- mex%>%select(starts_with(x))
  token = names(y)%>%str_sub(start=2)
  z = sum(token==token_grid)
  if(z==length(y)){
    return(y)
    }else{
    print("Formats de donnees incompaltibes entre les categories")
  }
})

Y= data.frame(Y)
token_sort=c(mex$ADM2_EN)
for(i in seq(1,length(token_grid))){
  temp = select(Y, ends_with(token_grid[i]))
  token_sort = append(token_sort,temp)
}

temp_1=list()
for(i in seq(1,3)){
  append(temp_1, names(y[[1]])%>%str_sub(start = 2))
}

lapply(x,function(X){
  cbind(dts_list, select(mex,contains(X)))
})
```
